FROM python:3.12-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY req.txt .
RUN pip install --no-cache-dir -r req.txt

COPY app ./app
RUN mkdir -p /app/logs /certs

EXPOSE 8443
CMD ["uvicorn", "app.service_b.main:app", "--host", "0.0.0.0", "--port", "8443", "--ssl-certfile", "/certs/cert.pem", "--ssl-keyfile", "/certs/key.pem"]